name: "size"
on:
  pull_request:
    branches:
      - master
      - develop
      - feat/ligthouse-enhancements
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: yarn run size
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}